# EDA - Estudiantes

## Importación de datos

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import seaborn as sns

In [6]:
ruta_estudiantes = (
    Path("..") / ".." / "Recursos"
    / "Dataset estudiantes concatenado"
    / "dataset_estudiantes_consolidado.parquet"
)
print(ruta_estudiantes.exists())
df_e = pd.read_parquet(ruta_estudiantes)
print(df_e.shape)

True
(4560711, 21)

## Exploración de los datos - DataFrame Estudiante

### Primeras aproximaciones

In [7]:
for i, col in enumerate(df_e.columns, start=1):
    print(f"{i}. {col}")

1. Id persona
2. Sexo
3. Rol
4. Departamento
5. Subsistema
6. Ciclo
7. Grado
8. Zona
9. Contexto
10. Año lectivo
11. Cantidad de días ingreso a CREA
12. Cantidad de entregas de tareas
13. Cantidad de Comentarios posteados
14. Cantidad de Acciones totales
15. Cantidad de días de ingreso a Matific
16. Cantidad de episodios finalizados en Matific
17. Cantidad de días de ingreso a PAM
18. Cantidad de actividades finalizadas en PAM
19. Cantidad de días de ingreso a Biblioteca
20. Cantidad de préstamos en biblioteca
21. archivo_origen

In [8]:
df_e.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4560711 entries, 0 to 4560710
Data columns (total 21 columns):
 #   Column                                        Dtype
---  ------                                        -----
 0   Id persona                                    string
 1   Sexo                                          object
 2   Rol                                           object
 3   Departamento                                  object
 4   Subsistema                                    object
 5   Ciclo                                         object
 6   Grado                                         string
 7   Zona                                          object
 8   Contexto                                      object
 9   Año lectivo                                   int64
 10  Cantidad de días ingreso a CREA               int64
 11  Cantidad de entregas de tareas                int64
 12  Cantidad de Comentarios posteados             int64
 13  Cantidad de Acciones totales                  int64
 14  Cantidad de días de ingreso a Matific         float64
 15  Cantidad de episodios finalizados en Matific  float64
 16  Cantidad de días de ingreso a PAM             float64
 17  Cantidad de actividades finalizadas en PAM    float64
 18  Cantidad de días de ingreso a Biblioteca      int64
 19  Cantidad de préstamos en biblioteca           int64
 20  archivo_origen                                object
dtypes: float64(4), int64(7), object(8), string(2)
memory usage: 730.7+ MB

In [11]:
df_e.shape

(4560711, 21)

In [12]:
df_e.head()

,Id persona,Sexo,Rol,Departamento,Subsistema,Ciclo,Grado,Zona,...,Cantidad de Acciones totales,Cantidad de días de ingreso a Matific,Cantidad de episodios finalizados en Matific,Cantidad de días de ingreso a PAM,Cantidad de actividades finalizadas en PAM,Cantidad de días de ingreso a Biblioteca,Cantidad de préstamos en biblioteca,archivo_origen
0,2087935,Femenino,Estudiante,Montevideo,DGEIP,Inicial,Nivel 5,Urbana,...,0,0.0,0.0,0.0,0.0,0,0,actividad-de-estudiantes-2024.csv
1,2079367,Femenino,Estudiante,Maldonado,DGES,3er. Ciclo Ebi,7,Sin Dato,...,0,NaN,NaN,0.0,0.0,0,0,actividad-de-estudiantes-2024.csv
2,2080855,Masculino,Estudiante,Montevideo,DGES,3er. Ciclo Ebi,7,Sin Dato,...,192,NaN,NaN,0.0,0.0,0,0,actividad-de-estudiantes-2024.csv
3,840930,Femenino,Estudiante,Rivera,DGEIP,Primaria,6º,Rural,...,7,0.0,0.0,0.0,0.0,0,0,actividad-de-estudiantes-2024.csv
4,2064917,Masculino,Estudiante,San Jose,DGEIP,Primaria,2º,Rural,...,0,0.0,0.0,0.0,0.0,0,0,actividad-de-estudiantes-2024.csv

In [13]:
df_e.tail()

,Id persona,Sexo,Rol,Departamento,Subsistema,Ciclo,Grado,Zona,...,Cantidad de Acciones totales,Cantidad de días de ingreso a Matific,Cantidad de episodios finalizados en Matific,Cantidad de días de ingreso a PAM,Cantidad de actividades finalizadas en PAM,Cantidad de días de ingreso a Biblioteca,Cantidad de préstamos en biblioteca,archivo_origen
4560706,2043846,Masculino,Estudiante,Paysandu,DGEIP,Primaria,4º,Urbana,...,0,0.0,0.0,NaN,NaN,0,0,estudiantes_datos_abiertos_agesic.csv
4560707,2043847,Masculino,Estudiante,Montevideo,DGEIP,Primaria,2º,Urbana,...,0,0.0,0.0,NaN,NaN,0,0,estudiantes_datos_abiertos_agesic.csv
4560708,2043848,Masculino,Estudiante,Montevideo,DGEIP,Primaria,4º,Urbana,...,0,0.0,0.0,NaN,NaN,0,0,estudiantes_datos_abiertos_agesic.csv
4560709,2043898,Masculino,Estudiante,Cerro Largo,DGEIP,Inicial,Nivel 3,Rural,...,0,0.0,0.0,NaN,NaN,0,0,estudiantes_datos_abiertos_agesic.csv
4560710,2059542,Masculino,Estudiante,Montevideo,DGEIP,Inicial,Nivel 4,Urbana,...,0,0.0,0.0,NaN,NaN,0,0,estudiantes_datos_abiertos_agesic.csv

In [15]:
df_e.isna().sum().T

Id persona                                            0
Sexo                                                  0
Rol                                                   0
Departamento                                          0
Subsistema                                            0
Ciclo                                                 0
Grado                                                 0
Zona                                                  0
Contexto                                              0
Año lectivo                                           0
Cantidad de días ingreso a CREA                       0
Cantidad de entregas de tareas                        0
Cantidad de Comentarios posteados                     0
Cantidad de Acciones totales                          0
Cantidad de días de ingreso a Matific           2203934
Cantidad de episodios finalizados en Matific    2203934
Cantidad de días de ingreso a PAM               1267839
Cantidad de actividades finalizadas en PAM      1267839
Cantidad de días de ingreso a Biblioteca              0
Cantidad de préstamos en biblioteca                   0
archivo_origen                                        0
dtype: int64